//defines.h

#define SETBIT(WORD,BIT)   (WORD |= 1<<BIT)
#define CLRBIT(WORD,BIT)    (WORD |= 1<<BIT)
#define CLEAR_BIT(WORD,BIT)  (WORD &= ~(1 << BIT))
#define READBIT(WORD,BIT)  ((WORD>>BIT)&1)
#define WRITEBIT(WORD,BITPOS,BITLEVEL) \
        (BITLEVEL?(WORD|=1<<BITPOS):(WORD&=~(1<<BITPOS)))
        //WORD=((WORD&~(1<<BITPOS))|(BIT<<BITPOS))     				
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) \
        DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#define WRITE2PORTBIT(PORTNO,BITPOS,BITLEVEL) \
        ((PORTNO==0)? \
				(BITLEVEL?(IOSET0=1<<BITPOS):(IOCLR0=1<<BITPOS)): \
				(BITLEVEL?(IOSET1=1<<BITPOS):(IOCLR1=1<<BITPOS)))

#define WRITEBYTE(WORD,BITSTARTPOS,BYTE) \
        WORD=((WORD&~(0xFF<<BITSTARTPOS))|(BYTE<<BITSTARTPOS))

#define WRITENIBBLE(WORD,BITSTARTPOS,NIBBLE)\
		WORD=(WORD&~(15<<BITSTARTPOS)|(NIBBLE<<BITSTARTPOS))
#define READNIBBLE(WORD,BITSTARTPOS)\
		((WORD>>BITSTARTPOS)&15)
